### ISSUE TITLE
error in installation Swift version 

### ISSUE THREAD

**Issue by guilhermedinardi** [attheodo/homebrew-formulae#1]
I need a help in this problem 

swift build -c release --disable-sandbox
/private/tmp/wifimon-20211004-19749-1xnhb27: error: package at '/private/tmp/wifimon-20211004-19749-1xnhb27' is using Swift tools version 5.5.0 but the installed version is 5.3.0
make: *** [build] Error 1

how to fix it?

**Comment by attheodo** [comment]
Hey @guilhermedinardi,

I've lowered the tools version to 5.2

Please try again and let me know if that works.

**Comment by guilhermedinardi** [comment]
I still can not  :c

**Comment by attheodo** [comment]
Same error?

**Comment by guilhermedinardi** [comment]
close issue
